### ISSUE TITLE
Cannot reproduce the code with pykeen 1.10.1, pytorch 2.0.1, and python 3.11.3 

### ISSUE THREAD

**Issue by sayalaruano** [dlopezyse/Drug-Repurposing-using-KGE#1]
Hi! First of all, congrats for the great project. I was looking for a project using pykeen in biomedical KGs for drug discovery, and this is a perfect example. Now, I'm working on a project for a class from my MSc and I would like to do something similar. 

However, I was trying to reproduce the code on my computer, but it seems that the methods and functions are deprecated. Do you mind telling me what version of pykeen and pytorch did you use to be able to reproduce your work?

As a recommendation, it's good to add a requirements.txt or similar file to assure reproducibility. 

Thanks in advance for your help!

**Comment by dlopezyse** [comment]
Hi Sebastian,

Thanks for your message. I've just updated the repository and also developed an [App](https://dr-using-kge.streamlit.app/#get-drugs-recommendations) to show the results.
I used pykeen==1.10.1 to [train the embedding models](https://github.com/dlopezyse/Drug-Repurposing-using-KGE/blob/main/train_embeddings.py) in Google Colab, and torch==2.1.0 to [perform the predictions](https://github.com/dlopezyse/Drug-Repurposing-using-KGE/blob/main/predictions.py).

Let me know if this helps.

Regards

Diego
